name: Deploy

on:
  push:
    branches:
      - final_project

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "netflix-streambuddy" 
          heroku_email: "streambuddy455@gmail.com"
          branch: "final_project"
          